/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BubbleSortVisualizer: typeof import('./components/algorithm/sort/BubbleSortVisualizer.vue')['default']
    BucketSortVisualizer: typeof import('./components/algorithm/sort/BucketSortVisualizer.vue')['default']
    CountingSortVisualizer: typeof import('./components/algorithm/sort/CountingSortVisualizer.vue')['default']
    HeapSortVisualizer: typeof import('./components/algorithm/sort/HeapSortVisualizer.vue')['default']
    InsertionSortVisualizer: typeof import('./components/algorithm/sort/InsertionSortVisualizer.vue')['default']
    LC1004MaxConsecutiveOnesIII: typeof import('./components/oj/leetcode/optimal-algorithm/sliding-window/LC1004MaxConsecutiveOnesIII.vue')['default']
    LC1089DuplicateZerosExtraSpace: typeof import('./components/oj/leetcode/optimal-algorithm/two-pointers/LC1089DuplicateZerosExtraSpace.vue')['default']
    LC1089DuplicateZerosInPlace: typeof import('./components/oj/leetcode/optimal-algorithm/two-pointers/LC1089DuplicateZerosInPlace.vue')['default']
    LC11ContainerWithMostWater: typeof import('./components/oj/leetcode/optimal-algorithm/two-pointers/LC11ContainerWithMostWater.vue')['default']
    LC138CopyRandomList: typeof import('./components/oj/leetcode/LC138CopyRandomList.vue')['default']
    LC15ThreeSum: typeof import('./components/oj/leetcode/optimal-algorithm/two-pointers/LC15ThreeSum.vue')['default']
    LC1658MinOperations: typeof import('./components/oj/leetcode/optimal-algorithm/sliding-window/LC1658MinOperations.vue')['default']
    LC18FourSum: typeof import('./components/oj/leetcode/optimal-algorithm/two-pointers/LC18FourSum.vue')['default']
    LC202HappyNumber: typeof import('./components/oj/leetcode/optimal-algorithm/two-pointers/LC202HappyNumber.vue')['default']
    LC209MinSubArrayLen: typeof import('./components/oj/leetcode/optimal-algorithm/sliding-window/LC209MinSubArrayLen.vue')['default']
    LC283MoveZeroes: typeof import('./components/oj/leetcode/optimal-algorithm/two-pointers/LC283MoveZeroes.vue')['default']
    LC30FindSubstring: typeof import('./components/oj/leetcode/optimal-algorithm/sliding-window/LC30FindSubstring.vue')['default']
    LC3LongestSubstring: typeof import('./components/oj/leetcode/optimal-algorithm/sliding-window/LC3LongestSubstring.vue')['default']
    LC438FindAnagrams: typeof import('./components/oj/leetcode/optimal-algorithm/sliding-window/LC438FindAnagrams.vue')['default']
    LC611ValidTriangleNumber: typeof import('./components/oj/leetcode/optimal-algorithm/two-pointers/LC611ValidTriangleNumber.vue')['default']
    LC76MinWindow: typeof import('./components/oj/leetcode/optimal-algorithm/sliding-window/LC76MinWindow.vue')['default']
    LC904TotalFruit: typeof import('./components/oj/leetcode/optimal-algorithm/sliding-window/LC904TotalFruit.vue')['default']
    MergeSortVisualizer: typeof import('./components/algorithm/sort/MergeSortVisualizer.vue')['default']
    QuickSortHoareVisualizer: typeof import('./components/algorithm/sort/QuickSortHoareVisualizer.vue')['default']
    QuickSortHoleVisualizer: typeof import('./components/algorithm/sort/QuickSortHoleVisualizer.vue')['default']
    QuickSortPointersVisualizer: typeof import('./components/algorithm/sort/QuickSortPointersVisualizer.vue')['default']
    RadixSortVisualizer: typeof import('./components/algorithm/sort/RadixSortVisualizer.vue')['default']
    SelectionSortVisualizer: typeof import('./components/algorithm/sort/SelectionSortVisualizer.vue')['default']
    ShellSortVisualizer: typeof import('./components/algorithm/sort/ShellSortVisualizer.vue')['default']
  }
}
