/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BubbleSortVisualizer: typeof import('./components/algorithm/sort/BubbleSortVisualizer.vue')['default']
    BucketSortVisualizer: typeof import('./components/algorithm/sort/BucketSortVisualizer.vue')['default']
    CountingSortVisualizer: typeof import('./components/algorithm/sort/CountingSortVisualizer.vue')['default']
    HeapSortVisualizer: typeof import('./components/algorithm/sort/HeapSortVisualizer.vue')['default']
    InsertionSortVisualizer: typeof import('./components/algorithm/sort/InsertionSortVisualizer.vue')['default']
    LC138CopyRandomList: typeof import('./components/oj/leetcode/LC138CopyRandomList.vue')['default']
    MergeSortVisualizer: typeof import('./components/algorithm/sort/MergeSortVisualizer.vue')['default']
    QuickSortHoareVisualizer: typeof import('./components/algorithm/sort/QuickSortHoareVisualizer.vue')['default']
    QuickSortHoleVisualizer: typeof import('./components/algorithm/sort/QuickSortHoleVisualizer.vue')['default']
    QuickSortPointersVisualizer: typeof import('./components/algorithm/sort/QuickSortPointersVisualizer.vue')['default']
    RadixSortVisualizer: typeof import('./components/algorithm/sort/RadixSortVisualizer.vue')['default']
    SelectionSortVisualizer: typeof import('./components/algorithm/sort/SelectionSortVisualizer.vue')['default']
    ShellSortVisualizer: typeof import('./components/algorithm/sort/ShellSortVisualizer.vue')['default']
  }
}
